### ISSUE TITLE
无法解析网易URL问题

### ISSUE THREAD

**Issue by MoeGakuen** [zgq354/APlayer-Typecho-Plugin#10]
我本地测试没问题，但是扔上主机就无法解析网易音乐Url，提示Error happens，歌词和图片到没问题。
是需要什么扩展库才能吗？PHP 版本5.6

**Comment by zgq354** [comment]
是所有音乐都无法解析吗，如果只是个别音乐不能解析的话，应该和主机的地理位置有关系，某些音乐可能因为版权问题只能在大陆播放，然后服务器在国外的主机上可能就获取不到了，临时解决的话你可以复制歌曲地址的url之后在插入音乐的标签增加一个 url属性 （插入歌单的话暂时就没什么办法了。。）

后期我会考虑设置一个api国内代理

**Comment by MoeGakuen** [comment]
是所有音乐。我是香港主机，是网易版权问题吗

**Comment by zgq354** [comment]
可以提供一下不能解析的音乐的id吗，我测试测试，我的美国主机倒没什么问题

**Comment by MoeGakuen** [comment]
示例都不行。。29947420

试了一下，代理解析没问题。
境外就是不能解析，能播放

**Comment by Domonlee** [comment]
我也遇到了这个问题。不知改如何解决。

> [player id='11362719' type='collect' url='xxxx']
> 是这样子嘛？

**Comment by Domonlee** [comment]
已经解决了。

**Comment by skykain** [comment]
@Domonlee 请问是如何解决的？

**Comment by skykain** [comment]
没办法，只好找了个国内服务器程序做个中转抓接口数据

**Comment by Nliver** [comment]
> 没办法，只好找了个国内服务器程序做个中转抓接口数据

怎么做的？

**Comment by zgq354** [comment]
这里集成了网易的接口目前不能用了，准备抽空更新一波 @Nliver

**Comment by Nliver** [comment]
> 这里集成了网易的接口目前不能用了，准备抽空更新一波 @Nliver

好的，期待
