### ISSUE TITLE
启用后整个博客500error

### ISSUE THREAD

**Issue by Xiaodx912** [zgq354/APlayer-Typecho-Plugin#16]
看见之前issue有这个问题但是关了。求解
cache权限777，启用后所有页面500，单个文件访问不受影响，后台不受影响，禁用后立即恢复

**Comment by journey-ad** [comment]
可能是使用了新语法导致的问题，升级你的PHP版本或开启日志查看出错的地方手动修正

**Comment by Xiaodx912** [comment]
php已经升级到5.6.30，log中报错
> Catchable fatal error:  Argument 1 passed to Typecho_Widget::push() must be of the type array, null given, called in /var/www/typecho/var/Widget/Abstract/Contents.php on line 760 and defined in /var/www/typecho/var/Typecho/Widget.php on line 274

附上完全版错误日志如下
[www-error.log.txt](https://github.com/zgq354/APlayer-Typecho-Plugin/files/905837/www-error.log.txt)
谷歌之未见解决方法，望各位大佬帮助解决

**Comment by zgq354** [comment]
你的typecho是什么版本，安装的是哪个版本的插件呢，目测大概是某个插件挂载点出错了

**Comment by Xiaodx912** [comment]
Typecho版本 1.0 (14.10.10)，Aplayer版本1.4.11
博客url[https://kira.cat](url)，根目录是/var/www/typecho
如有需要可以参照php的error log访问目录下文件
谢谢大佬帮助
