### ISSUE TITLE
大佬还打算更新嘛~~~

### ISSUE THREAD

**Issue by ty859555470** [zgq354/APlayer-Typecho-Plugin#20]
看了17年的计划，有点小期待呢~~~

**Comment by zgq354** [comment]
会有的，就是，被其它事情拖住了时间，争取尽快提上日程吧

**Comment by zgq354** [comment]
恰饭问题解决，精力终于又回到了 Web 上，继续填坑！！！

**Comment by dzy0302** [comment]
期待更新！

**Comment by GrassBlock1** [comment]
> 会有的，就是，被其它事情拖住了时间，争取尽快提上日程吧

所以大佬 还在喵？我这边一直都是"Server error"

**Comment by zgq354** [comment]
> > 会有的，就是，被其它事情拖住了时间，争取尽快提上日程吧
> 
> 所以大佬 还在喵？我这边一直都是"Server error"

暂时网易API这块都没法用，不过自定义是可以的。

**Comment by GrassBlock1** [comment]
> > > 会有的，就是，被其它事情拖住了时间，争取尽快提上日程吧
> > 
> > 
> > 所以大佬 还在喵？我这边一直都是"Server error"
> 
> 暂时网易API这块都没法用，不过自定义是可以的。

星，期待（咕咕咕

**Comment by GrassBlock1** [comment]
![Screenshot_20200331193155](https://user-images.githubusercontent.com/46253950/78021759-5b222e00-7386-11ea-947d-6e32b34e389f.jpg)

> > > 会有的，就是，被其它事情拖住了时间，争取尽快提上日程吧
> > 
> > 
> > 所以大佬 还在喵？我这边一直都是"Server error"
> 
> 暂时网易API这块都没法用，不过自定义是可以的。

咕咕咕 我这里在插件中心点启用就弹出 server error (，根本无法启用和配置

附图一张（

**Comment by zgq354** [comment]
得检查一下权限问题，启用的时候会自动清除缓存

**Comment by whitenight** [comment]
根本与权限无关 全新安装就是这个错误 这个是用typecho哪个版本开发的呢 让其他朋友尝试也是一样 server error 

> 得检查一下权限问题，启用的时候会自动清除缓存

**Comment by GrassBlock1** [comment]
> 根本与权限无关 全新安装就是这个错误 这个是用typecho哪个版本开发的呢 让其他朋友尝试也是一样 server error
> 
> > 得检查一下权限问题，启用的时候会自动清除缓存

我貌似解决了 下载解压之后还得把文件夹名字改成APlayer（（（（

**Comment by zgq354** [comment]
哈咯各位，插件更新的事情可以集中在 这个 issue 讨论吧，鸽子太久了，觉得该放手的时候就应该放手
https://github.com/zgq354/APlayer-Typecho-Plugin/issues/17
