### ISSUE TITLE
目前需解决的问题

### ISSUE THREAD

**Issue by zgq354** [zgq354/APlayer-Typecho-Plugin#5]
1. ajax 异步加载播放列表
   默认是页面开始解析时侯加载列表，可能某些情况下会导致网页载入缓慢
2. 缓存接口抽象化，将支持 file，memcache，数据库，redis 等缓存方式
3. 编辑器中添加插入音乐按钮，方便添加音乐
4. 虾米 api 解析

所以本插件未来可能会有较大的改动，敬请期待~

**Comment by Ereebay** [comment]
有不少网易的歌曲无法解析

**Comment by zgq354** [comment]
多半是版权问题~

**Comment by Ereebay** [comment]
没版权的也有不少不能解析（日文歌偏多）

**Comment by zgq354** [comment]
可能是api的问题

**Comment by Darkyyx** [comment]
如果能添加https支持就好了，强迫症忍不了绿锁变白纸啊。。

**Comment by ghost** [comment]
good

**Comment by zgq354** [comment]
@Darkyyx 音乐可能不支持https啊
