### ISSUE TITLE
IE中效果感人

### ISSUE THREAD

**Issue by ju0594** [zgq354/APlayer-Typecho-Plugin#6]
![1](http://ww1.sinaimg.cn/large/0060yV4Lgw1f2jnald1qyj30k20gemym.jpg)

还有就是有时候莫名出现的error happens

**Comment by zgq354** [comment]
挂件的作者是在chrome调试的所以可能有些兼容性问题。。有空搞一搞

**Comment by zgq354** [comment]
找到原因了，IE 的 line-height 不支持 initial
![image](https://cloud.githubusercontent.com/assets/9024954/14232671/824a6eae-f9e4-11e5-8952-a3117da2cbb2.png)

**Comment by ju0594** [comment]
能解决吗？试了下原版的APlayer好像没有这个问题...

**Comment by zgq354** [comment]
已修复~~ https://github.com/zgq354/APlayer-Typecho-Plugin/commit/d9aec83a89031e03e3887722061eae654aaba6ee
